### ISSUE TITLE
Fix for torrent9, cpasbien and t411

### ISSUE THREAD

**Issue by Pireo** [CravateRouge/qBittorrentSearchPlugins#1]
Hi friend, seeing you're french, I wonder if you have interest in fixing these existing plugins. Thanks.

**Comment by CravateRouge** [comment]
Hi, of course, I will gladly fix these plugins.

**Comment by Pireo** [comment]
Hmmm torrent9 doesn't seem to work still, thanks btw

**Comment by CravateRouge** [comment]
Torrent9 works for me, did you try my [torrent9 plugin](https://raw.githubusercontent.com/CravateRouge/qBittorrentSearchPlugins/master/torrent9.py)? Or could you tell me which use case you did? (Python 2 or 3? qBitTorrent last version? Search keyword?)

**Comment by Pireo** [comment]
Ah, wait, I think I've found why, in my country the site does show cloudflare before accessing it, so that's why the plugin also doesn't show results.

**Comment by Pireo** [comment]
p.s. Yggtorrent works and redirects to the download page but if I click on a result it doesn't open up any window.

**Comment by CravateRouge** [comment]
When you try to download from qBitorrent or directly from the description page? Because it works for me from qBittorrent and you need authentication to download from the description page.

**Comment by Pireo** [comment]
From qBt. Is it because I have no authentication?

**Comment by CravateRouge** [comment]
Yes, like it is said on the README you must have authentication because it's a private torrent tracker.

**Comment by Pireo** [comment]
I know it was private, but I thought it would allow you to see the content, just the download wouldn't start. Thanks. Now if you want to fix cpasbien...

**Comment by CravateRouge** [comment]
Oh ok, I understand what you meant now and indeed it doesn't allow download without authentication.
Cpasbien retrieve the same content as torrent9 but the search engine is very poor and you can't sort by most seeded. And t411 is dead and was replaced by another site with a very poor search engine too without sorting by most seeded option.

**Comment by Pireo** [comment]
Yeah, there are some unofficial mirrors of t411 as you can see here https://torrents.me/site/t411/
and I don't know if this is legit http://www.t411.one/
not that I'm interested, it's just thet they were in the list unfixed and so...

**Comment by CravateRouge** [comment]
It doesn't seem to be legit. I understand but I will not fix these plugins for the moment because the sites that they scrap are obsolete too.

**Comment by Pireo** [comment]
Sure, I see, thanks and now I can close this issue.
