### ISSUE TITLE
Oxtorrent.co doesn't work

### ISSUE THREAD

**Issue by ghost** [CravateRouge/qBittorrentSearchPlugins#11]
https://www.oxtorrent.co/ (official domain) doesn't work, just changing the url in the .py file doesn't help.

**Comment by CravateRouge** [comment]
I updated the download function and now it should work. It use the magnet link now because the link for the torrent file isn't available anymore as an anonymous user.
Also I renamed torrent9.py as oxtorrent.py.

**Comment by ghost** [comment]
Wow that was fast, thanks! I've tested it and I can confirm it works, however I will adjust the favicon.

**Comment by CravateRouge** [comment]
Great, if you find anything, do not hesitate to raise an issue. Could you put the favicon readjusted in a pull request? Thanks.
