### ISSUE TITLE
YggTorrent do not work at all...

### ISSUE THREAD

**Issue by p060477** [CravateRouge/qBittorrentSearchPlugins#17]
pls update this yr plug in page :

https://github.com/CravateRouge/qBittorrentSearchPlugins
where you wrote:
YggTorrent
Download the plugin file or copy the following link.
Because YggTorrent requires your login info, this plugin requires a bit more work than most.
Firstly you'll need an account

NOW the site really do not work at all..:
https://yggtorrent.ch/user/register
returns:
404 Not Found

how to solve..??

**Comment by CravateRouge** [comment]
It's fixed, I updated the URL, next time do a pull request with the changes or if you don't know how to do it, ask nicely. A "Thank you" never killed anyone...

**Comment by p060477** [comment]
" A "Thank you" never killed anyone..."...:
i totally agree...also for someone who let you fix a yr mistake...
"medice cura te ipsum!"...(it's an old latin phrase...don't worry...!!... ;) )
;)
