### ISSUE TITLE
[oxtorrent.py] invalid version string

### ISSUE THREAD

**Issue by Obegg** [CravateRouge/qBittorrentSearchPlugins#19]
![image](https://user-images.githubusercontent.com/13978119/148852924-17aa9223-c30f-45a6-b8d9-b55792e09b2b.png)

```
Search plugin 'oxtorrent.py' contains invalid version string ('1.2.2
')
```

**Comment by CravateRouge** [comment]
Try the latest version 2.3, it should work.
