### ISSUE TITLE
Returning results but can't download .torrent

### ISSUE THREAD

**Issue by Eyji** [CravateRouge/qBittorrentSearchPlugins#4]
See capture below.
Using qBittorent 4.1.5

![yggtorrent](https://user-images.githubusercontent.com/10639815/57197177-4a91e980-6f64-11e9-979c-223da752b1c8.png)

**Comment by CravateRouge** [comment]
It seems that the url has changed and it caused some troubles, now it's fix.

**Comment by Eyji** [comment]
The url you modified breaks the search results
New url seems to be https://www2.yggtorrent.ch rather than just www.yggtorrent.ch

But even with this, still have the same issue.

**Comment by CravateRouge** [comment]
You're right, I corrected the url and I tested both search and download and it works!

I had to create a new YggTorrent account because the old one wasn't recognized. So try to connect to the YggTorrent site by hand to verify your account validity.
