### ISSUE TITLE
Plugin yggtorrent is not supported

### ISSUE THREAD

**Issue by gdlx** [CravateRouge/qBittorrentSearchPlugins#5]
I'm trying to install the YGGtorrent plugin, but the qBittorrent log keep saying this :

`Plugin yggtorrent is not supported`

I'm using qBittorrent as a docker image: https://hub.docker.com/r/linuxserver/qbittorrent/

**Comment by gdlx** [comment]
I found the problem: Python 3 is not installed in the docker image.

I sent a PR to fix this: https://github.com/linuxserver/docker-qbittorrent/pull/48

I'm now able to install the plugin but the search gives no result. Is there a way to log the request and result ?

**Comment by CravateRouge** [comment]
> I'm now able to install the plugin but the search gives no result. Is there a way to log the request and result ?

To debug the plugin, I import the plugin in a python interactive console and I call the methods. You can add logging lines in the methods to know the output of those methods.

I tested it this morning and it was working for me so you should maybe check the validity of your YGG torrent account first.

**Comment by gdlx** [comment]
Thanks @CravateRouge, I'm now able to get results (it was linked to SOCKS5 proxy usage when `python3` is installed, enabling it only for torrents made the trick), but now I have another problem: when trying to download a torrent from the results, nothing happens.

I tried from the CLI and it successfully downloads the file in /tmp with an output like this:

````
/tmp/tmppdobqeum https://www2.yggtorrent.ch/engine/download_torrent?id=XXXX
````

I've checked the downloaded file is a valid torrent with `transmission-show` tool and it is correct, but when I click the `Download` button from the search results page, and then validate the download, the torrent is not added in the queue, and I just get this message in `qbittorrent.log`:

````
Downloading 'https://www2.yggtorrent.ch/engine/download_torrent?id=XXXX', please wait...
````

Note I'm using the Web GUI only.

Any idea ?

**Comment by CravateRouge** [comment]
Not at all, but if you find the answer, I would be glad to know.
