### ISSUE TITLE
Can't install with qbittorrent 4.2

### ISSUE THREAD

**Issue by vfauth** [CravateRouge/qBittorrentSearchPlugins#7]
Hi,

I have qbittorrent 4.2 in Docker (using the Linux Server image). I am able to install scripts, either using the URL and the webUI or by dropping the scripts in the engines directory.

But this doesn't work for both of these scripts. I get no error, there is nothing in the logs, the .pyc file is correctly generated (when I drop the script, with the URL the .py file is not even downloaded), but the script is not installed.

The Docker container has both Python 2 and 3.

**Comment by CravateRouge** [comment]
What you can do to have more information on this error is to open a python 3 interpreter, import the script file and use the search method to start.
For example:

```
import yggtorrent

yggtorrent.yggtorrent.search("linux")
```
